// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

type Database = {
  public: {
    Tables: {}
    Views: {}
    Functions: {}
    Enums: {}
    CompositeTypes: {}
  }
}

const SUPABASE_URL = 'https://xnhvdnxtqpbpzifoennw.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuaHZkbnh0cXBicHppZm9lbm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MjI5ODUsImV4cCI6MjA3NDE5ODk4NX0.TP6ykHGp4KKcWEYza2Zg-_HMDcKiRE1CcXpZ_pk8R1o';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});